---
apiVersion: v1
kind: Service
metadata:
  name: taskd
  labels:
    app: taskd
spec:
  ports:
    - protocol: TCP
      port: 53589
      targetPort: 53589
  type: "LoadBalancer"
  selector:
    app: taskd
